/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Compatibility {
    #[serde(rename = "compatible", skip_serializing_if = "Option::is_none")]
    pub compatible: Option<bool>,
    #[serde(rename = "agent", skip_serializing_if = "Option::is_none")]
    pub agent: Option<crate::models::Agent>,
    #[serde(rename = "buildType", skip_serializing_if = "Option::is_none")]
    pub build_type: Option<crate::models::BuildType>,
    #[serde(rename = "unmetRequirements", skip_serializing_if = "Option::is_none")]
    pub unmet_requirements: Option<crate::models::Requirements>,
}

impl Compatibility {
    pub fn new() -> Compatibility {
        Compatibility {
            compatible: None,
            agent: None,
            build_type: None,
            unmet_requirements: None,
        }
    }
}


