/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Features {
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "feature", skip_serializing_if = "Option::is_none")]
    pub feature: Option<Vec<crate::models::Feature>>,
}

impl Features {
    pub fn new() -> Features {
        Features {
            count: None,
            feature: None,
        }
    }
}


