/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileChange {
    #[serde(rename = "before-revision", skip_serializing_if = "Option::is_none")]
    pub before_revision: Option<String>,
    #[serde(rename = "after-revision", skip_serializing_if = "Option::is_none")]
    pub after_revision: Option<String>,
    #[serde(rename = "changeType", skip_serializing_if = "Option::is_none")]
    pub change_type: Option<String>,
    #[serde(rename = "changeTypeComment", skip_serializing_if = "Option::is_none")]
    pub change_type_comment: Option<String>,
    #[serde(rename = "file", skip_serializing_if = "Option::is_none")]
    pub file: Option<String>,
    #[serde(rename = "relative-file", skip_serializing_if = "Option::is_none")]
    pub relative_file: Option<String>,
    #[serde(rename = "directory", skip_serializing_if = "Option::is_none")]
    pub directory: Option<bool>,
}

impl FileChange {
    pub fn new() -> FileChange {
        FileChange {
            before_revision: None,
            after_revision: None,
            change_type: None,
            change_type_comment: None,
            file: None,
            relative_file: None,
            directory: None,
        }
    }
}


