/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Investigation {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "assignee", skip_serializing_if = "Option::is_none")]
    pub assignee: Option<crate::models::User>,
    #[serde(rename = "assignment", skip_serializing_if = "Option::is_none")]
    pub assignment: Option<crate::models::Comment>,
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<crate::models::ProblemScope>,
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<crate::models::ProblemTarget>,
    #[serde(rename = "resolution", skip_serializing_if = "Option::is_none")]
    pub resolution: Option<crate::models::Resolution>,
    #[serde(rename = "responsible", skip_serializing_if = "Option::is_none")]
    pub responsible: Option<crate::models::User>,
}

impl Investigation {
    pub fn new() -> Investigation {
        Investigation {
            id: None,
            state: None,
            href: None,
            assignee: None,
            assignment: None,
            scope: None,
            target: None,
            resolution: None,
            responsible: None,
        }
    }
}


