/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssuesUsages {
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "issueUsage", skip_serializing_if = "Option::is_none")]
    pub issue_usage: Option<Vec<crate::models::IssueUsage>>,
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
}

impl IssuesUsages {
    pub fn new() -> IssuesUsages {
        IssuesUsages {
            href: None,
            issue_usage: None,
            count: None,
        }
    }
}


