/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueUsage {
    #[serde(rename = "changes", skip_serializing_if = "Option::is_none")]
    pub changes: Option<crate::models::Changes>,
    #[serde(rename = "issue", skip_serializing_if = "Option::is_none")]
    pub issue: Option<crate::models::Issue>,
}

impl IssueUsage {
    pub fn new() -> IssueUsage {
        IssueUsage {
            changes: None,
            issue: None,
        }
    }
}


