/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Metric {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "prometheusName", skip_serializing_if = "Option::is_none")]
    pub prometheus_name: Option<String>,
    #[serde(rename = "metricValues", skip_serializing_if = "Option::is_none")]
    pub metric_values: Option<crate::models::MetricValues>,
    #[serde(rename = "metricTags", skip_serializing_if = "Option::is_none")]
    pub metric_tags: Option<crate::models::MetricTags>,
}

impl Metric {
    pub fn new() -> Metric {
        Metric {
            name: None,
            description: None,
            prometheus_name: None,
            metric_values: None,
            metric_tags: None,
        }
    }
}


