/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelType {
    #[serde(rename = "rawValue", skip_serializing_if = "Option::is_none")]
    pub raw_value: Option<String>,
}

impl ModelType {
    pub fn new() -> ModelType {
        ModelType {
            raw_value: None,
        }
    }
}


