/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MuteLocator {
    #[serde(rename = "affectedProject", skip_serializing_if = "Option::is_none")]
    pub affected_project: Option<String>,
    #[serde(rename = "creationDate", skip_serializing_if = "Option::is_none")]
    pub creation_date: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "item", skip_serializing_if = "Option::is_none")]
    pub item: Option<String>,
    #[serde(rename = "problem", skip_serializing_if = "Option::is_none")]
    pub problem: Option<String>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(rename = "reporter", skip_serializing_if = "Option::is_none")]
    pub reporter: Option<String>,
    #[serde(rename = "resolution", skip_serializing_if = "Option::is_none")]
    pub resolution: Option<String>,
    #[serde(rename = "test", skip_serializing_if = "Option::is_none")]
    pub test: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    #[serde(rename = "unmuteDate", skip_serializing_if = "Option::is_none")]
    pub unmute_date: Option<String>,
}

impl MuteLocator {
    pub fn new() -> MuteLocator {
        MuteLocator {
            affected_project: None,
            creation_date: None,
            id: None,
            item: None,
            problem: None,
            project: None,
            reporter: None,
            resolution: None,
            test: None,
            _type: None,
            unmute_date: None,
        }
    }
}


