/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewBuildTypeDescription {
    #[serde(rename = "copyAllAssociatedSettings", skip_serializing_if = "Option::is_none")]
    pub copy_all_associated_settings: Option<bool>,
    #[serde(rename = "projectsIdsMap", skip_serializing_if = "Option::is_none")]
    pub projects_ids_map: Option<crate::models::Properties>,
    #[serde(rename = "buildTypesIdsMap", skip_serializing_if = "Option::is_none")]
    pub build_types_ids_map: Option<crate::models::Properties>,
    #[serde(rename = "vcsRootsIdsMap", skip_serializing_if = "Option::is_none")]
    pub vcs_roots_ids_map: Option<crate::models::Properties>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "sourceBuildTypeLocator", skip_serializing_if = "Option::is_none")]
    pub source_build_type_locator: Option<String>,
    #[serde(rename = "sourceBuildType", skip_serializing_if = "Option::is_none")]
    pub source_build_type: Option<crate::models::BuildType>,
}

impl NewBuildTypeDescription {
    pub fn new() -> NewBuildTypeDescription {
        NewBuildTypeDescription {
            copy_all_associated_settings: None,
            projects_ids_map: None,
            build_types_ids_map: None,
            vcs_roots_ids_map: None,
            name: None,
            id: None,
            source_build_type_locator: None,
            source_build_type: None,
        }
    }
}


