/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PermissionAssignments {
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "permissionAssignment", skip_serializing_if = "Option::is_none")]
    pub permission_assignment: Option<Vec<crate::models::PermissionAssignment>>,
}

impl PermissionAssignments {
    pub fn new() -> PermissionAssignments {
        PermissionAssignments {
            count: None,
            permission_assignment: None,
        }
    }
}


