/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PinInfo {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<bool>,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<crate::models::Comment>,
}

impl PinInfo {
    pub fn new() -> PinInfo {
        PinInfo {
            status: None,
            comment: None,
        }
    }
}


