/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProblemScope {
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<crate::models::Project>,
    #[serde(rename = "buildTypes", skip_serializing_if = "Option::is_none")]
    pub build_types: Option<crate::models::BuildTypes>,
    #[serde(rename = "buildType", skip_serializing_if = "Option::is_none")]
    pub build_type: Option<crate::models::BuildType>,
}

impl ProblemScope {
    pub fn new() -> ProblemScope {
        ProblemScope {
            project: None,
            build_types: None,
            build_type: None,
        }
    }
}


