/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProblemTarget {
    #[serde(rename = "anyProblem", skip_serializing_if = "Option::is_none")]
    pub any_problem: Option<bool>,
    #[serde(rename = "tests", skip_serializing_if = "Option::is_none")]
    pub tests: Option<crate::models::Tests>,
    #[serde(rename = "problems", skip_serializing_if = "Option::is_none")]
    pub problems: Option<crate::models::Problems>,
}

impl ProblemTarget {
    pub fn new() -> ProblemTarget {
        ProblemTarget {
            any_problem: None,
            tests: None,
            problems: None,
        }
    }
}


