/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProgressInfo {
    #[serde(rename = "percentageComplete", skip_serializing_if = "Option::is_none")]
    pub percentage_complete: Option<i32>,
    #[serde(rename = "elapsedSeconds", skip_serializing_if = "Option::is_none")]
    pub elapsed_seconds: Option<i64>,
    #[serde(rename = "estimatedTotalSeconds", skip_serializing_if = "Option::is_none")]
    pub estimated_total_seconds: Option<i64>,
    #[serde(rename = "leftSeconds", skip_serializing_if = "Option::is_none")]
    pub left_seconds: Option<i64>,
    #[serde(rename = "currentStageText", skip_serializing_if = "Option::is_none")]
    pub current_stage_text: Option<String>,
    #[serde(rename = "outdated", skip_serializing_if = "Option::is_none")]
    pub outdated: Option<bool>,
    #[serde(rename = "probablyHanging", skip_serializing_if = "Option::is_none")]
    pub probably_hanging: Option<bool>,
    #[serde(rename = "lastActivityTime", skip_serializing_if = "Option::is_none")]
    pub last_activity_time: Option<String>,
    #[serde(rename = "outdatedReasonBuild", skip_serializing_if = "Option::is_none")]
    pub outdated_reason_build: Option<crate::models::Build>,
}

impl ProgressInfo {
    pub fn new() -> ProgressInfo {
        ProgressInfo {
            percentage_complete: None,
            elapsed_seconds: None,
            estimated_total_seconds: None,
            left_seconds: None,
            current_stage_text: None,
            outdated: None,
            probably_hanging: None,
            last_activity_time: None,
            outdated_reason_build: None,
        }
    }
}


