/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Related {
    #[serde(rename = "builds", skip_serializing_if = "Option::is_none")]
    pub builds: Option<crate::models::Builds>,
}

impl Related {
    pub fn new() -> Related {
        Related {
            builds: None,
        }
    }
}


