/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryState {
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "branch", skip_serializing_if = "Option::is_none")]
    pub branch: Option<Vec<crate::models::BranchVersion>>,
}

impl RepositoryState {
    pub fn new() -> RepositoryState {
        RepositoryState {
            timestamp: None,
            count: None,
            branch: None,
        }
    }
}


