/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Revision {
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "internalVersion", skip_serializing_if = "Option::is_none")]
    pub internal_version: Option<String>,
    #[serde(rename = "vcsBranchName", skip_serializing_if = "Option::is_none")]
    pub vcs_branch_name: Option<String>,
    #[serde(rename = "vcs-root-instance", skip_serializing_if = "Option::is_none")]
    pub vcs_root_instance: Option<crate::models::VcsRootInstance>,
    #[serde(rename = "checkout-rules", skip_serializing_if = "Option::is_none")]
    pub checkout_rules: Option<String>,
}

impl Revision {
    pub fn new() -> Revision {
        Revision {
            version: None,
            internal_version: None,
            vcs_branch_name: None,
            vcs_root_instance: None,
            checkout_rules: None,
        }
    }
}


