/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Roles {
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<Vec<crate::models::Role>>,
}

impl Roles {
    pub fn new() -> Roles {
        Roles {
            role: None,
        }
    }
}


