/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SnapshotDependencies {
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "snapshot-dependency", skip_serializing_if = "Option::is_none")]
    pub snapshot_dependency: Option<Vec<crate::models::SnapshotDependency>>,
}

impl SnapshotDependencies {
    pub fn new() -> SnapshotDependencies {
        SnapshotDependencies {
            count: None,
            snapshot_dependency: None,
        }
    }
}


