/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Steps {
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "step", skip_serializing_if = "Option::is_none")]
    pub step: Option<Vec<crate::models::Step>>,
}

impl Steps {
    pub fn new() -> Steps {
        Steps {
            count: None,
            step: None,
        }
    }
}


