/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TestCounters {
    #[serde(rename = "ignored", skip_serializing_if = "Option::is_none")]
    pub ignored: Option<i32>,
    #[serde(rename = "failed", skip_serializing_if = "Option::is_none")]
    pub failed: Option<i32>,
    #[serde(rename = "muted", skip_serializing_if = "Option::is_none")]
    pub muted: Option<i32>,
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<i32>,
    #[serde(rename = "all", skip_serializing_if = "Option::is_none")]
    pub all: Option<i32>,
}

impl TestCounters {
    pub fn new() -> TestCounters {
        TestCounters {
            ignored: None,
            failed: None,
            muted: None,
            success: None,
            all: None,
        }
    }
}


