/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tokens {
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<Vec<crate::models::Token>>,
}

impl Tokens {
    pub fn new() -> Tokens {
        Tokens {
            count: None,
            token: None,
        }
    }
}


