/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VcsRootEntries {
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "vcs-root-entry", skip_serializing_if = "Option::is_none")]
    pub vcs_root_entry: Option<Vec<crate::models::VcsRootEntry>>,
}

impl VcsRootEntries {
    pub fn new() -> VcsRootEntries {
        VcsRootEntries {
            count: None,
            vcs_root_entry: None,
        }
    }
}


